require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/*'
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - config/routes.rb
Metrics/AbcSize:
  Max: 32
Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
    - db/migrate/*.rb
